-- BEAUTIFUL_NOISE.DATA.BANDS_EVENTS
-- Generated by sql/dump_ddl.py. Do not edit by hand.
-- WARNING: GET_DDL emits CREATE OR REPLACE. Re-running this against a live
-- schema is destructive. Read sql/README.md before applying anything here.

create or replace TABLE BANDS_EVENTS (
	EVENT_BAND_KEY NUMBER(38,0) NOT NULL autoincrement start 1 increment 1 noorder,
	EVENT_ID NUMBER(38,0),
	BAND_ID NUMBER(38,0),
	IS_HEADLINER BOOLEAN DEFAULT TRUE,
	primary key (EVENT_BAND_KEY),
	unique (EVENT_ID, BAND_ID)
);
