-- BEAUTIFUL_NOISE.DATA.CREDITS
-- Generated by sql/dump_ddl.py. Do not edit by hand.
-- WARNING: GET_DDL emits CREATE OR REPLACE. Re-running this against a live
-- schema is destructive. Read sql/README.md before applying anything here.

create or replace TABLE CREDITS (
	CREDIT_ID NUMBER(38,0) NOT NULL autoincrement start 1 increment 1 noorder,
	CREDIT_NAME VARCHAR(16777216) NOT NULL,
	unique (CREDIT_NAME),
	primary key (CREDIT_ID)
);
