-- BEAUTIFUL_NOISE.DATA.EVENTS
-- Generated by sql/dump_ddl.py. Do not edit by hand.
-- WARNING: GET_DDL emits CREATE OR REPLACE. Re-running this against a live
-- schema is destructive. Read sql/README.md before applying anything here.

create or replace TABLE EVENTS (
	EVENT_ID NUMBER(38,0) NOT NULL autoincrement start 1 increment 1 noorder,
	EVENT_NAME VARCHAR(16777216),
	DATE DATE,
	VENUE_ID NUMBER(38,0),
	primary key (EVENT_ID),
	unique (EVENT_NAME, DATE, VENUE_ID)
);
