-- BEAUTIFUL_NOISE.DATA.POSTERS_RAW
-- Generated by sql/dump_ddl.py. Do not edit by hand.
-- WARNING: GET_DDL emits CREATE OR REPLACE. Re-running this against a live
-- schema is destructive. Read sql/README.md before applying anything here.

create or replace TABLE POSTERS_RAW (
	FILE_NAME VARCHAR(16777216),
	AI_COMPLETE VARIANT
);
