-- BEAUTIFUL_NOISE.DATA.POSTERS
-- Generated by sql/dump_ddl.py. Do not edit by hand.
-- WARNING: GET_DDL emits CREATE OR REPLACE. Re-running this against a live
-- schema is destructive. Read sql/README.md before applying anything here.

create or replace TABLE POSTERS (
	POSTER_ID NUMBER(38,0) NOT NULL autoincrement start 1 increment 1 noorder,
	FILE_NAME VARCHAR(16777216) NOT NULL,
	UPLOADED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
	EVENT_ID NUMBER(38,0),
	DESIGNER_ID NUMBER(38,0) DEFAULT 1,
	MD5_HASH VARCHAR(16777216),
	UPLOAD_TYPE VARCHAR(16777216) DEFAULT 'COMMUNITY',
	primary key (POSTER_ID),
	unique (MD5_HASH)
);
