-- BEAUTIFUL_NOISE.DATA.POSTER_VENUES
-- Generated by sql/dump_ddl.py. Do not edit by hand.
-- WARNING: GET_DDL emits CREATE OR REPLACE. Re-running this against a live
-- schema is destructive. Read sql/README.md before applying anything here.

create or replace TABLE POSTER_VENUES (
	POSTER_VENUE_KEY NUMBER(38,0) NOT NULL autoincrement start 1 increment 1 noorder,
	POSTER_ID NUMBER(38,0) NOT NULL,
	VENUE_ID NUMBER(38,0) NOT NULL,
	unique (POSTER_ID, VENUE_ID),
	primary key (POSTER_VENUE_KEY)
);
