import os
from pathlib import Path

from dotenv import load_dotenv

# Local development reads .env; Railway injects the same names as real environment
# variables and ships no .env, where this is a no-op. This replaces the base64
# STREAMLIT_SECRETS_B64 blob, which existed only because Streamlit cannot read a nested
# [connections.snowflake] table from the environment — with flat keys, the whole
# decode-to-disk step in start.sh goes away.
load_dotenv(Path(__file__).resolve().parent.parent / ".env")


def _require(name: str) -> str:
    """Read a required setting, failing at import with a message that says what to fix.

    Deliberately loud. A missing credential should stop the app at startup with the
    variable's name, not surface later as an opaque connection error on whichever page a
    visitor happens to open first.
    """
    value = os.environ.get(name)
    if not value:
        raise RuntimeError(
            f"Required environment variable {name} is not set. "
            f"Locally: add it to .env. On Railway: Service -> Variables."
        )
    return value


# --- Paths ----------------------------------------------------------------
# Both resolved from this file's location rather than the working directory, so reads
# work no matter where `streamlit run` is invoked from.

# User-facing copy (faq.md, tos.md).
CONTENT_DIR = Path(__file__).resolve().parent.parent / "content"

# Browser-tab icon: "BN" in white on the theme's #ff0033, 256x256 (browsers downscale).
#
# It has to be opaque, and that is the whole point of it. Streamlit's index.html hardcodes
# <link rel="shortcut icon" href="./favicon.png"> — its own logo — and the browser paints
# that before the websocket connects; page_icon only *replaces* it afterwards. The previous
# icon here was a fully transparent PNG, which is indistinguishable from "no change" to a
# browser, so the Streamlit logo simply stayed. There is no way to omit a favicon; the only
# way to lose the Streamlit one is to paint over it.
FAVICON = str(Path(__file__).resolve().parent.parent / "static" / "favicon.png")

# --- Database -------------------------------------------------------------
# The pooled (-pooler) Neon host, authenticating as bn_app: SELECT and INSERT only, no
# UPDATE/DELETE/CREATE. Generated by sql/postgres/apply.py; never typed by a human.
# Named NEON_APP_URL rather than DATABASE_URL to stay distinct from NEON_ADMIN_URL, which
# is the owner connection used for schema work and must never reach the app.
DATABASE_URL = _require("NEON_APP_URL")

# --- Object storage -------------------------------------------------------
# Posters live in Cloudflare R2 and are served to browsers straight off R2's public
# custom domain, so image bytes never pass through Railway. Keeping it that way is what
# holds host egress at effectively zero.
R2_ENDPOINT = _require("R2_ENDPOINT")
R2_BUCKET = _require("R2_BUCKET")
R2_ACCESS_KEY_ID = _require("R2_ACCESS_KEY_ID")
R2_SECRET_ACCESS_KEY = _require("R2_SECRET_ACCESS_KEY")
# Public read base, e.g. https://posters.beautifulnoise.melbourne — no trailing slash.
R2_PUBLIC_BASE = _require("R2_PUBLIC_BASE").rstrip("/")

# --- AI extraction --------------------------------------------------------
# Kept in code, not the environment, so a model change ships via a normal git push rather
# than a manual variable edit. Must be image-capable.
#
# Llama 4 Maverick, reached through OpenRouter. Benchmarked against Claude Haiku 4.5,
# Qwen3-VL-32B and GPT-5-mini over 20 real posters on 2026-08-17: Maverick needed the
# fewest corrections (9/20 posters clean against Haiku's 3), read dates perfectly, ran
# fastest (~2s vs 2.7s), and costs roughly a fifth of Haiku. Haiku's failure mode was the
# expensive one — fluent, confident, invented band names (MARTYRED DEATH for Mannequin
# Death Squad, DRA2LOG for Dialog) that a reviewer has to notice and retype.
MODEL = "meta-llama/llama-4-maverick"
OPENROUTER_BASE_URL = "https://openrouter.ai/api/v1"

# OpenRouter serves one model ID from several upstream hosts at different quantisations,
# and they are not equivalent: DigitalOcean was measured four times more *consistent* than
# DeepInfra and consistently WORSE, misreading four posters DeepInfra reads correctly, at
# five times the latency (11.5s vs 2.0s). So DeepInfra is preferred — but fallbacks stay
# ENABLED here, unlike in the benchmark where they were pinned off for reproducibility.
# In production a DeepInfra outage should degrade extraction quality, not stop uploads.
# require_parameters keeps any host that would ignore the JSON schema out of the rotation:
# without it a non-compliant host returns prose and run_extraction's json.loads explodes.
# `zdr` restricts routing to zero-data-retention endpoints, and it is load-bearing for a
# promise made to visitors: content/faq.md and content/tos.md both tell uploaders their
# poster is only handled by providers that don't retain it. Verified 2026-08-17 that
# DeepInfra still qualifies, so this costs nothing — same provider, same latency. If the
# ZDR pool ever empties, requests fail and the upload page shows "scanning unavailable",
# which is the correct failure mode: fail closed rather than quietly route a stranger's
# poster to a provider that keeps it. Do not remove this to fix an outage.
OPENROUTER_PROVIDER = {
    "order": ["DeepInfra"],
    "allow_fallbacks": True,
    "require_parameters": True,
    "zdr": True,
}

# Room for the structured-output JSON and nothing more; this is an extraction task.
MAX_OUTPUT_TOKENS = 1024

# --- UI -------------------------------------------------------------------
IMG_FORMAT = "JPEG"
NAV_BTN_WIDTH = 220

# --- Image ingestion hardening --------------------------------------------
# Decode-time ceiling on pixel count. ~40 MP comfortably allows large phone photos and
# scans (a 12 MP iPhone shot is fine) while blocking decompression "pixel bombs" — small
# files that decode to enormous dimensions and exhaust memory. The final stored image is
# only 1200 px on its longest side, so this guards the *input*, not quality.
MAX_IMAGE_PIXELS = 40_000_000
# DPI used to rasterise the first page of an uploaded PDF. Clamped down at runtime if a
# page is large enough that rendering at this DPI would exceed MAX_IMAGE_PIXELS.
PDF_RENDER_DPI = 150
# PIL .format values we accept. The file_uploader type= list is only an extension hint —
# PIL decodes by magic bytes, so this content-based allowlist is what actually constrains
# which codecs run on untrusted input.
ALLOWED_IMAGE_FORMATS = {"JPEG", "PNG", "WEBP"}
