import os
from pathlib import Path

from dotenv import load_dotenv

# Local development reads .env; Railway injects the same names as real environment
# variables and ships no .env, where this is a no-op. This replaces the base64
# STREAMLIT_SECRETS_B64 blob, which existed only because Streamlit cannot read a nested
# [connections.snowflake] table from the environment — with flat keys, the whole
# decode-to-disk step in start.sh goes away.
load_dotenv(Path(__file__).resolve().parent.parent / ".env")


def _require(name: str) -> str:
    """Read a required setting, failing at import with a message that says what to fix.

    Deliberately loud. A missing credential should stop the app at startup with the
    variable's name, not surface later as an opaque connection error on whichever page a
    visitor happens to open first.
    """
    value = os.environ.get(name)
    if not value:
        raise RuntimeError(
            f"Required environment variable {name} is not set. "
            f"Locally: add it to .env. On Railway: Service -> Variables."
        )
    return value


# --- Paths ----------------------------------------------------------------
# Both resolved from this file's location rather than the working directory, so reads
# work no matter where `streamlit run` is invoked from.

# User-facing copy (faq.md, tos.md).
CONTENT_DIR = Path(__file__).resolve().parent.parent / "content"

# A deliberately blank browser-tab icon. Streamlit offers no way to *omit* the favicon —
# page_icon=None falls back to the Streamlit logo — so the only route to an empty tab is
# to hand it an image containing nothing. This is a 32x32 fully transparent PNG.
BLANK_ICON = str(Path(__file__).resolve().parent.parent / "static" / "blank_favicon.png")

# --- Database -------------------------------------------------------------
# The pooled (-pooler) Neon host, authenticating as bn_app: SELECT and INSERT only, no
# UPDATE/DELETE/CREATE. Generated by sql/postgres/apply.py; never typed by a human.
# Named NEON_APP_URL rather than DATABASE_URL to stay distinct from NEON_ADMIN_URL, which
# is the owner connection used for schema work and must never reach the app.
DATABASE_URL = _require("NEON_APP_URL")

# --- Object storage -------------------------------------------------------
# Posters live in Cloudflare R2 and are served to browsers straight off R2's public
# custom domain, so image bytes never pass through Railway. Keeping it that way is what
# holds host egress at effectively zero.
R2_ENDPOINT = _require("R2_ENDPOINT")
R2_BUCKET = _require("R2_BUCKET")
R2_ACCESS_KEY_ID = _require("R2_ACCESS_KEY_ID")
R2_SECRET_ACCESS_KEY = _require("R2_SECRET_ACCESS_KEY")
# Public read base, e.g. https://posters.beautifulnoise.melbourne — no trailing slash.
R2_PUBLIC_BASE = _require("R2_PUBLIC_BASE").rstrip("/")

# --- AI extraction --------------------------------------------------------
# Kept in code, not the environment, so a model change ships via a normal git push rather
# than a manual variable edit. Must be image-capable.
MODEL = "claude-haiku-4-5"
# Room for the structured-output JSON and nothing more; this is an extraction task.
MAX_OUTPUT_TOKENS = 1024

# --- UI -------------------------------------------------------------------
IMG_FORMAT = "JPEG"
NAV_BTN_WIDTH = 220

# --- Image ingestion hardening --------------------------------------------
# Decode-time ceiling on pixel count. ~40 MP comfortably allows large phone photos and
# scans (a 12 MP iPhone shot is fine) while blocking decompression "pixel bombs" — small
# files that decode to enormous dimensions and exhaust memory. The final stored image is
# only 1200 px on its longest side, so this guards the *input*, not quality.
MAX_IMAGE_PIXELS = 40_000_000
# DPI used to rasterise the first page of an uploaded PDF. Clamped down at runtime if a
# page is large enough that rendering at this DPI would exceed MAX_IMAGE_PIXELS.
PDF_RENDER_DPI = 150
# PIL .format values we accept. The file_uploader type= list is only an extension hint —
# PIL decodes by magic bytes, so this content-based allowlist is what actually constrains
# which codecs run on untrusted input.
ALLOWED_IMAGE_FORMATS = {"JPEG", "PNG", "WEBP"}
