-- BEAUTIFUL NOISE — Postgres schema (Neon)
--
-- Hand-maintained. Unlike sql/tables/*.sql (which were GET_DDL dumps of the live
-- Snowflake schema), this file is the source of truth: the database is built FROM it.
--
-- Deliberately NOT idempotent — no `IF NOT EXISTS`, no `OR REPLACE`. Running it twice
-- fails loudly on the first CREATE rather than silently reconciling against drift.
-- Order matters: parents before children, because the foreign keys are real here.

-- ---------------------------------------------------------------------------
-- Dimensions
--
-- All three follow the same shape and are written by get_or_insert(). The UNIQUE
-- constraint on the name column is what makes ON CONFLICT work — it is the conflict
-- target, not decoration.
-- ---------------------------------------------------------------------------

CREATE TABLE bands (
    band_id   bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    band_name text NOT NULL UNIQUE
);

CREATE TABLE venues (
    venue_id   bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    venue_name text NOT NULL UNIQUE
);

CREATE TABLE credits (
    credit_id   bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    credit_name text NOT NULL UNIQUE
);

-- ---------------------------------------------------------------------------
-- Events
--
-- THE most important constraint in this file. `event_name` is legitimately NULL for
-- the majority of gigs (most posters name no event), and Postgres treats NULL != NULL,
-- so a plain UNIQUE would let every unnamed gig at the same venue on the same date
-- insert as a *separate* event. Because band_events is keyed on event_id, that would
-- split one gig's lineup across duplicate events — silently, with no error.
--
-- NULLS NOT DISTINCT (Postgres 15+) makes two NULL event_names compare equal, which is
-- exactly what get_or_insert_event() was hand-rolling with Snowpark's equal_null().
-- The application logic becomes a declarative constraint.
-- ---------------------------------------------------------------------------

CREATE TABLE events (
    event_id   bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_name text,
    date       date   NOT NULL,
    venue_id   bigint NOT NULL REFERENCES venues (venue_id),
    CONSTRAINT events_natural_key UNIQUE NULLS NOT DISTINCT (event_name, date, venue_id)
);

-- ---------------------------------------------------------------------------
-- Extractions — one row per AI scan
--
-- Written the moment the model responds, BEFORE anything is stored and before the user
-- has reviewed anything. Its purpose is a long-term baseline of where the model goes
-- wrong; it is a thing you query occasionally, not machinery the upload path carries.
--
-- Keyed on scan_id rather than a storage filename, because a scan is not a file: most
-- scans never become one. The Snowflake ancestors (EXTRACTIONS_RAW and
-- EXTRACTIONS_PROCESSED, joined on FILE_NAME) were shaped by a constraint that no longer
-- applies — objects had to be staged before AI_COMPLETE could read them.
--
-- `model` matters more than it looks. Without it, crossing a model change blends
-- generations into one meaningless average, and the whole point of the table is
-- comparison over time.
--
-- OUTCOME IS DERIVED, NEVER STORED. It isn't known at insert time, and the app role has
-- no UPDATE to set it later — which is the right constraint, since a derived value cannot
-- drift from reality:
--   rejected as not-a-poster : is_valid = false
--   saved                    : a poster row references this scan_id
--   abandoned mid-review     : is_valid = true, and no poster references it
-- ---------------------------------------------------------------------------

CREATE TABLE extractions (
    scan_id    uuid        PRIMARY KEY,
    scanned_at timestamptz NOT NULL DEFAULT now(),
    model      text        NOT NULL,
    is_valid   boolean     NOT NULL,
    raw        jsonb       NOT NULL,
    matched    jsonb
);

-- ---------------------------------------------------------------------------
-- Posters
--
-- file_name is the key the object is stored under in R2. It gains a UNIQUE constraint it
-- never had in Snowflake because it is the conflict target for the poster upsert — the
-- code already treated it as a key (it MERGEd on it), the schema just never said so.
-- It stays distinct from scan_id: one is where bytes live and could change if the stored
-- format ever did, the other is which scan produced this poster.
--
-- scan_id is what makes accuracy measurable. Joining a poster back to its extraction
-- gives the model's guess next to the values a human actually confirmed.
--
-- upload_type gains a CHECK. CLAUDE.md documents the domain as {RIGHTS_HOLDER,
-- COMMUNITY}; Snowflake had no way to enforce it, Postgres does, and gallery.py branches
-- on the value.
-- ---------------------------------------------------------------------------

CREATE TABLE posters (
    poster_id   bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    file_name   text        NOT NULL UNIQUE,
    scan_id     uuid        NOT NULL REFERENCES extractions (scan_id),
    uploaded_at timestamptz NOT NULL DEFAULT now(),
    event_id    bigint      NOT NULL REFERENCES events (event_id),
    md5_hash    text        NOT NULL UNIQUE,
    upload_type text        NOT NULL DEFAULT 'COMMUNITY'
                CHECK (upload_type IN ('RIGHTS_HOLDER', 'COMMUNITY'))
);

-- ---------------------------------------------------------------------------
-- Junctions
--
-- The Snowflake versions each carried a surrogate autoincrement key (BAND_EVENT_KEY,
-- POSTER_VENUE_KEY, POSTER_CREDIT_KEY) alongside a UNIQUE on the real key. Nothing ever
-- read those surrogates — not the app, not the view. A pure junction table's natural key
-- is already unique and already minimal, so here it IS the primary key. One less column,
-- one less index, and ON CONFLICT can target the PK directly.
--
-- ON DELETE CASCADE on the poster side means a takedown removes its own links rather
-- than erroring on a dangling reference. Note the app role has no DELETE at all — this
-- is about admin cleanup.
-- ---------------------------------------------------------------------------

CREATE TABLE band_events (
    event_id     bigint  NOT NULL REFERENCES events (event_id) ON DELETE CASCADE,
    band_id      bigint  NOT NULL REFERENCES bands (band_id),
    is_headliner boolean NOT NULL DEFAULT true,
    PRIMARY KEY (event_id, band_id)
);

CREATE TABLE poster_venues (
    poster_id bigint NOT NULL REFERENCES posters (poster_id) ON DELETE CASCADE,
    venue_id  bigint NOT NULL REFERENCES venues (venue_id),
    PRIMARY KEY (poster_id, venue_id)
);

CREATE TABLE poster_credits (
    poster_id bigint NOT NULL REFERENCES posters (poster_id) ON DELETE CASCADE,
    credit_id bigint NOT NULL REFERENCES credits (credit_id),
    PRIMARY KEY (poster_id, credit_id)
);

-- Finding abandoned scans means anti-joining posters, so make that side cheap.
CREATE INDEX posters_scan_id_idx ON posters (scan_id);

-- ---------------------------------------------------------------------------
-- Contact-page submissions
--
-- Applied by hand; there is no review tooling yet. status/resolved_at/admin_notes are
-- for that future tooling and are never written by the app (which has INSERT but not
-- UPDATE, so it could not change them even by accident).
-- ---------------------------------------------------------------------------

CREATE TABLE requests (
    request_id      bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    request_type    text NOT NULL,
    entity_type     text NOT NULL,
    scope           text NOT NULL,
    poster_ids      bigint[],
    current_value   text,
    requested_value text,
    notes           text,
    status          text        NOT NULL DEFAULT 'PENDING',
    submitted_at    timestamptz NOT NULL DEFAULT now(),
    resolved_at     timestamptz,
    admin_notes     text
);

CREATE INDEX requests_status_idx ON requests (status) WHERE status = 'PENDING';
