-- BEAUTIFUL_NOISE.DATA.POSTER_GALLERY_V
-- Generated by sql/dump_ddl.py. Do not edit by hand.
-- WARNING: GET_DDL emits CREATE OR REPLACE. Re-running this against a live
-- schema is destructive. Read sql/README.md before applying anything here.

create or replace view POSTER_GALLERY_V(
	POSTER_ID,
	FILE_NAME,
	EVENT_NAME,
	DATE,
	VENUE_NAME,
	VENUES,
	UPLOADED_AT,
	MD5_HASH,
	UPLOAD_TYPE,
	BANDS,
	HEADLINERS,
	SUPPORTS,
	CREDITS
) as
WITH poster_credits_agg AS (
    SELECT pc.poster_id, ARRAY_AGG(cr.credit_name) AS credits
    FROM BEAUTIFUL_NOISE.DATA.POSTER_CREDITS pc
    JOIN BEAUTIFUL_NOISE.DATA.CREDITS cr ON pc.credit_id = cr.credit_id
    GROUP BY pc.poster_id
),
poster_venues_agg AS (
    SELECT pv.poster_id, ARRAY_AGG(vn.venue_name) AS venues
    FROM BEAUTIFUL_NOISE.DATA.POSTER_VENUES pv
    JOIN BEAUTIFUL_NOISE.DATA.VENUES vn ON pv.venue_id = vn.venue_id
    GROUP BY pv.poster_id
)
SELECT
    p.poster_id, p.file_name, e.event_name, e.date, v.venue_name,
    COALESCE(pva.venues, ARRAY_CONSTRUCT(v.venue_name)) AS venues,
    p.uploaded_at, p.md5_hash, p.upload_type,
    ARRAY_AGG(b.band_name) AS bands,
    ARRAY_AGG(CASE WHEN be.is_headliner = TRUE  THEN b.band_name END) AS headliners,
    ARRAY_AGG(CASE WHEN be.is_headliner = FALSE THEN b.band_name END) AS supports,
    COALESCE(pca.credits, ARRAY_CONSTRUCT()) AS credits
FROM BEAUTIFUL_NOISE.DATA.POSTERS p
JOIN BEAUTIFUL_NOISE.DATA.EVENTS      e  ON p.event_id = e.event_id
JOIN BEAUTIFUL_NOISE.DATA.VENUES      v  ON e.venue_id = v.venue_id
JOIN BEAUTIFUL_NOISE.DATA.BAND_EVENTS be ON e.event_id = be.event_id
JOIN BEAUTIFUL_NOISE.DATA.BANDS       b  ON be.band_id = b.band_id
LEFT JOIN poster_credits_agg pca ON p.poster_id = pca.poster_id
LEFT JOIN poster_venues_agg  pva ON p.poster_id = pva.poster_id
GROUP BY p.poster_id, p.file_name, e.event_name, e.date, v.venue_name,
         p.uploaded_at, p.md5_hash, p.upload_type, pca.credits, pva.venues;
