-- BEAUTIFUL_NOISE.DATA.CLEANUP_ORPHANED_STAGE_FILES
-- Generated by sql/dump_ddl.py. Do not edit by hand.
-- WARNING: GET_DDL emits CREATE OR REPLACE. Re-running this against a live
-- schema is destructive. Read sql/README.md before applying anything here.

create or replace task CLEANUP_ORPHANED_STAGE_FILES
	warehouse=COMPUTE_WH
	schedule='USING CRON 0 3 * * 0 Australia/Melbourne'
	as EXECUTE IMMEDIATE $$
BEGIN
    EXECUTE IMMEDIATE 'ALTER STAGE POSTERS REFRESH';
    DECLARE
        c CURSOR FOR 
            SELECT RELATIVE_PATH FROM DIRECTORY(@POSTERS) 
            WHERE RELATIVE_PATH NOT IN (SELECT file_name FROM POSTERS);
    BEGIN
        FOR rec IN c DO
            EXECUTE IMMEDIATE 'REMOVE @POSTERS/' || rec.RELATIVE_PATH;
        END FOR;
    END;
END;
$$;
