"""Regenerate the committed DDL snapshot in sql/ from the live BEAUTIFUL_NOISE.DATA schema.

Usage:
    python sql/dump_ddl.py

Reads the same .streamlit/secrets.toml the app uses (gitignored), connects with the same
key-pair auth as core.db.get_session(), and writes one .sql file per object.

Scope is deliberately narrow:
  * DATA only. STAGING is a stale clone belonging to the admin app and is not tracked here.
  * Schema objects only. GRANTS ARE NOT DUMPED — this repo is public, and role/privilege
    topology does not belong in it. Keep those in .context/ (gitignored).
  * No data. GET_DDL emits structure, never rows.

Cost note: unlike a SHOW command, GET_DDL runs as a query and will briefly resume the
warehouse. COMPUTE_WH is X-Small with a 60s auto-suspend, so this is cents, not dollars.
"""
import pathlib
import sys

try:                                  # 3.11+
    import tomllib
    def _load(p): return tomllib.loads(pathlib.Path(p).read_text(encoding="utf-8"))
except ModuleNotFoundError:           # 3.10 — needs `pip install toml`
    import toml
    def _load(p): return toml.load(p)

from cryptography.hazmat.primitives import serialization
import snowflake.connector

ROOT = pathlib.Path(__file__).resolve().parent.parent
OUT = ROOT / "sql"
SECRETS = ROOT / ".streamlit" / "secrets.toml"

# Object kinds to dump -> subdirectory. SHOW <kind>S IN SCHEMA drives discovery, so a new
# table appears in the snapshot automatically on the next run.
KINDS = [("TABLE", "tables"), ("VIEW", "views"), ("TASK", "tasks")]

# Objects excluded from the snapshot. Listed here rather than deleted by hand, so a regeneration
# doesn't quietly reintroduce them.
#
#   ADMIN_APP         stage for the abandoned Streamlit-in-Snowflake admin app; that approach
#                     proved too restrictive and is being reconsidered elsewhere.
#   POSTERS_PROCESSED a stray. Snowpark's save_as_table(mode="append") issues CREATE TABLE IF NOT
#                     EXISTS, so a stale-bytecode process recreated the pre-rename table and wrote
#                     to it. Its one audit row has been recovered into EXTRACTIONS_PROCESSED; the
#                     empty shell awaits a DROP. Remove this entry once it's gone.
EXCLUDE = {"ADMIN_APP", "POSTERS_PROCESSED"}


def connect(cfg):
    pkey = serialization.load_pem_private_key(
        cfg["private_key"].encode("utf-8"),
        password=cfg["private_key_passphrase"].encode("utf-8"),
    )
    der = pkey.private_bytes(
        encoding=serialization.Encoding.DER,
        format=serialization.PrivateFormat.PKCS8,
        encryption_algorithm=serialization.NoEncryption(),
    )
    return snowflake.connector.connect(
        account=cfg["account"], user=cfg["user"], role=cfg["role"],
        warehouse=cfg["warehouse"], database=cfg["database"], schema=cfg["schema"],
        private_key=der,
    )


def main():
    if not SECRETS.exists():
        sys.exit(f"No secrets at {SECRETS}")
    cfg = _load(SECRETS)["connections"]["snowflake"]
    db, schema = cfg["database"], "DATA"
    con = connect(cfg)
    cur = con.cursor()

    def show(sql, *fields):
        """Run a SHOW and return the named columns, looked up by name rather than position —
        SHOW result layouts differ per object type and shift between Snowflake releases."""
        cur.execute(sql)
        cols = [d[0].lower() for d in cur.description]
        idx = [cols.index(f) for f in fields]
        return [tuple(row[i] for i in idx) for row in cur.fetchall()]

    written = 0
    for kind, folder in KINDS:
        names = [n for (n,) in show(f"SHOW {kind}S IN SCHEMA {db}.{schema}", "name")
                 if n.upper() not in EXCLUDE]
        target = OUT / folder
        target.mkdir(parents=True, exist_ok=True)
        # Clear first, so a renamed or dropped object doesn't leave a stale file behind claiming
        # an object that no longer exists. Everything in these folders is generated.
        for old in target.glob("*.sql"):
            old.unlink()
        for name in sorted(names):
            fq = f"{db}.{schema}.{name}"
            try:
                cur.execute(f"SELECT GET_DDL('{kind}', '{fq}')")
                ddl = cur.fetchone()[0].strip()
            except Exception as e:
                print(f"  SKIP {kind} {name}: {type(e).__name__}: {e}")
                continue
            (target / f"{name.lower()}.sql").write_text(
                f"-- {fq}\n"
                f"-- Generated by sql/dump_ddl.py. Do not edit by hand.\n"
                f"-- WARNING: GET_DDL emits CREATE OR REPLACE. Re-running this against a live\n"
                f"-- schema is destructive. Read sql/README.md before applying anything here.\n\n"
                f"{ddl}\n",
                encoding="utf-8",
            )
            written += 1
            print(f"  {kind:6} {name}")

    # Stages carry no GET_DDL support; record their definitions descriptively instead.
    stages = [s for s in show(f"SHOW STAGES IN SCHEMA {db}.{schema}", "name", "type", "url")
              if s[0].upper() not in EXCLUDE]
    if stages:
        (OUT / "stages.md").write_text(
            "# Stages in BEAUTIFUL_NOISE.DATA\n\n"
            "GET_DDL does not support stages, so this is a descriptive record rather than\n"
            "runnable DDL. Generated by sql/dump_ddl.py.\n\n"
            + "\n".join(
                f"- `{n}` — type: `{t}`, url: `{u or '(internal stage, no external URL)'}`"
                for n, t, u in sorted(stages)
            )
            + "\n",
            encoding="utf-8",
        )
        written += 1

    con.close()
    print(f"\n{written} file(s) written to {OUT}")


if __name__ == "__main__":
    main()
